name: Python Linting and Type Checking with uv

on: [push]

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # uv uses the standard pip cache, enable caching

      - name: Install uv
        run: pip install uv

      - name: Create uv virtual environment and sync dependencies
        run: |
          uv sync
          source .venv/bin/activate
          uv tool install mypy ruff

      - name: Run Ruff (formatting and linting)
        run: |
          source .venv/bin/activate
          uv run ruff check .
          uv run ruff format --check .

      - name: Run MyPy (type checking)
        run: |
          source .venv/bin/activate
          uv run mypy .